name = "dioxus-cloudflare-workers"
main = "build/index.js"
compatibility_date = "2023-12-18"

[build]
command = "./build.sh"

# Serve static assets
[assets]
directory = "./build/public"
binding = "ASSETS"

[vars]
# Add any environment variables your app needs here
